apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: gohello
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: gohello
        track: stable
    spec:
      containers:
        - name: gohello
          image: "elektromin/gohello:0.1"
          ports:
            - name: http
              containerPort: 8080
          resources:
            limits:
              cpu: 0.2
              memory: "10Mi"
          livenessProbe:
            httpGet:
              path: /ping
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 5
            periodSeconds: 15
            timeoutSeconds: 5
          readinessProbe:
            httpGet:
              path: /ping
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 5
            timeoutSeconds: 1